package io.github.vatidaniel.metadata.postgres;

import io.github.vatidaniel.metadata.core.ColumnMetadata;
import io.github.vatidaniel.metadata.core.ConstraintType;
import io.github.vatidaniel.metadata.core.ReferenceActionType;
import io.github.vatidaniel.metadata.core.ReferenceMetadata;
import io.github.vatidaniel.metadata.core.TableMetadata;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * @author tinhnv
 */
class PostgresDdlExecutorTest {

    /** Captures the generated SQL instead of running it, so DDL generation can be asserted without a DB. */
    private static class CapturingExecutor extends PostgresDdlExecutor {
        private String capturedSql;

        CapturingExecutor(TableMetadata tableMetadata) {
            super(tableMetadata, (Connection) null);
        }

        @Override
        public void executeSql(String sql) {
            this.capturedSql = sql;
        }
    }

    private TableMetadata personTable() {
        ColumnMetadata id = ColumnMetadata.builder()
            .name("id").dataType(PostgresDataType.INTEGER).primaryKey(true).nullable(false).identity(true)
            .build();
        ColumnMetadata name = ColumnMetadata.builder()
            .name("name").dataType(PostgresDataType.VARCHAR).dataTypeExtension("255")
            .columnDefault(ColumnMetadata.DefaultColumnValue.builder()
                .dataType(PostgresDataType.VARCHAR).value("unknown").build())
            .build();
        ColumnMetadata parentId = ColumnMetadata.builder()
            .name("parent_id").dataType(PostgresDataType.INTEGER)
            .referenceMetadata(new ReferenceMetadata("parent", "id",
                ReferenceActionType.CASCADE, ReferenceActionType.SET_NULL))
            .build();
        return TableMetadata.builder()
            .name("person")
            .tablespace("my_space")
            .columnsMetadata(List.of(id, name, parentId))
            .build();
    }

    @Test
    void createTable_usesPostgresQuotingIdentityAndTablespace() throws Exception {
        CapturingExecutor executor = new CapturingExecutor(personTable());
        executor.createTable();
        String sql = executor.capturedSql;

        assertNotNull(sql);
        assertTrue(sql.contains("CREATE TABLE \"person\""), sql);
        assertTrue(sql.contains("\"id\" INTEGER"), sql);
        assertTrue(sql.contains("GENERATED BY DEFAULT AS IDENTITY"), sql);
        assertTrue(sql.contains("\"name\" VARCHAR(255)"), sql);
        assertTrue(sql.contains("DEFAULT 'unknown'"), sql);
        assertTrue(sql.contains("PRIMARY KEY(\"id\")"), sql);
        // FK with distinct ON DELETE / ON UPDATE actions; referenced names quoted per-dialect
        assertTrue(sql.contains("FOREIGN KEY (\"parent_id\") REFERENCES \"parent\"(\"id\")"), sql);
        assertTrue(sql.contains("ON DELETE CASCADE"), sql);
        assertTrue(sql.contains("ON UPDATE SET NULL"), sql);
        // Postgres storage clause, not MySQL's "Engine ="
        assertTrue(sql.contains("TABLESPACE my_space"), sql);
        assertTrue(!sql.contains("Engine"), sql);
    }

    @Test
    void updateColumnDefinition_usesAlterColumnType() throws Exception {
        CapturingExecutor executor = new CapturingExecutor(personTable());
        executor.updateColumnDefinition("name");
        String sql = executor.capturedSql;

        assertNotNull(sql);
        assertTrue(sql.contains("ALTER TABLE \"person\" ALTER COLUMN \"name\" TYPE VARCHAR(255)"), sql);
        // must NOT use the MySQL MODIFY form
        assertTrue(!sql.contains("MODIFY"), sql);
    }

    @Test
    void constraints_usePostgresDivergentForms() throws Exception {
        CapturingExecutor e = new CapturingExecutor(personTable());

        // NOT NULL via ALTER COLUMN, not MySQL's MODIFY
        e.addColumnConstraint(ConstraintType.NOT_NULL, "id");
        assertEquals("ALTER TABLE \"person\" ALTER COLUMN \"id\" SET NOT NULL", e.capturedSql);

        // PK add shares the standard form (delegates to super)
        e.addColumnConstraint(ConstraintType.PRIMARY_KEY, "id");
        assertEquals("ALTER TABLE \"person\" ADD PRIMARY KEY (\"id\")", e.capturedSql);

        // every named constraint drops the same way
        e.dropColumnConstraint(ConstraintType.PRIMARY_KEY, "person_pkey");
        assertEquals("ALTER TABLE \"person\" DROP CONSTRAINT person_pkey", e.capturedSql);

        e.dropColumnConstraint(ConstraintType.FOREIGN_KEY, "person_parent_id_fk");
        assertEquals("ALTER TABLE \"person\" DROP CONSTRAINT person_parent_id_fk", e.capturedSql);

        e.dropColumnConstraint(ConstraintType.NOT_NULL, "id");
        assertEquals("ALTER TABLE \"person\" ALTER COLUMN \"id\" DROP NOT NULL", e.capturedSql);
    }
}
