package io.github.vatisteve.dataaccess;

/**
 * PostgreSQL dialect: double-quoted identifiers, SQL-standard {@code GENERATED BY DEFAULT AS IDENTITY}
 * columns and the {@code TABLESPACE} storage clause.
 *
 * @author tinhnv
 * @since Jun 13, 2026
 */
public class PostgresDialect implements SqlDialect {

    @Override
    public String quoteIdentifier(String identifier) {
        return SqlQueryConstants.quoteIdentifier(identifier, "\"", "\"");
    }

    @Override
    public String autoIncrementClause() {
        return " GENERATED BY DEFAULT AS IDENTITY ";
    }

    @Override
    public String tablespaceClause(String tablespace) {
        return tablespace == null ? "" : " TABLESPACE " + tablespace;
    }

    @Override
    public String paginate(int limit, long offset) {
        return "LIMIT " + limit + " OFFSET " + offset + " ";
    }

}
