package io.github.vatidaniel.dataaccess;

/**
 * Describes the dialect-specific spellings that vary across relational databases, so that the shared
 * query / DDL building code can stay database-agnostic.
 *
 * @author tinhnv
 * @since Jun 13, 2026
 */
public interface SqlDialect {

    /**
     * Wrap an identifier (table/column name) with the dialect's quoting characters,
     * E.g. {@code `name`} for MySQL/MariaDB, {@code "name"} for PostgreSQL.
     */
    String quoteIdentifier(String identifier);

    /**
     * The clause that marks an auto-incrementing / identity column, e.g. {@code " AUTO_INCREMENT "}
     * for MySQL/MariaDB, {@code " GENERATED BY DEFAULT AS IDENTITY "} for PostgreSQL.
     */
    String autoIncrementClause();

    /**
     * The trailing storage clause appended to a {@code CREATE TABLE} statement for the given
     * {@code tablespace} value, e.g. {@code " Engine = InnoDB"} for MySQL/MariaDB,
     * {@code " TABLESPACE my_space"} for PostgreSQL. Returns an empty string when {@code tablespace}
     * is {@code null}.
     */
    String tablespaceClause(String tablespace);

    /**
     * The pagination clause for the given {@code limit} and {@code offset}, terminated with a trailing
     * space so it can be concatenated directly, e.g. {@code "LIMIT 10 OFFSET 20 "}.
     */
    String paginate(int limit, long offset);

}
